name: Cargo Audit

# Argonautica fails audit
on:
  push:
    branches: '*'
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Audit
        run: cargo audit
